services:
  rms-postgres:
    image: postgres:16-alpine
    container_name: ${CONTAINER_DB_NAME}
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      # Подключаем каталог для хранения файлов БД
      - /var/lib/postgresql/data:/var/lib/postgresql/data

      # Подключаем файлы конфигурации работы БД
      - ./rms-postgres/config/pg_hba.conf:/etc/postgresql/pg_hba.conf:ro
      - ./rms-postgres/config/postgresql.conf:/etc/postgresql/postgresql.conf:ro

      # Подключаем sql-скрипты, которые будут выполняться
      # при превом запуске контейнера.
      # Порядок вызова скриптов определяется порядком сортировки файлов
      - ./postgres/scripts/initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - app-network

  rms-web:
    build:
      context: ./rms-web
      dockerfile: Dockerfile
    container_name: ${CONTAINER_WEB_NAME}
    ports:
    - "80:80"
    volumes:
      - ./rms-web/www:/var/www/html
      - ./rms-web/httpd2/default.conf:/etc/httpd2/conf/sites-available/default.conf:ro
      #- ./rms-web/php-config:/etc/php/8.2/cli/
    environment:
      - DB_HOST=rms-postgres
      - DB_PORT=5432
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      rms-postgres:
        condition: service_healthy
    networks:
      - app-network

networks:
  app-network:
    driver: bridge